file_format: '1'
id: cosmos
name: cosmos
type: shield
url: https://github.com/Bastardkb/cosmos/
requires: [pro_micro]
studio: true
features:
  - keys
  - pointer
siblings:
  - cosmos_left
  - cosmos_right
